/**
 * Statistical core conformance tests.
 *
 * Ultima decides whether to tell a customer "your model changed" using nothing
 * but packages/core/src/stats.js. A false positive burns trust; a false
 * negative is a missed incident. Since the module is written from scratch with
 * zero dependencies, correctness is not self-evident -- so the numeric
 * assertions below are pinned against SciPy/NumPy/statsmodels ground truth,
 * committed in fixtures/scipy-reference.json and regenerated by
 * scripts/gen-stats-reference.py.
 *
 * The suite has three layers:
 *   1. Conformance  -- exact agreement with SciPy on realistic samples.
 *   2. Properties   -- invariants that must hold for ANY input (symmetry,
 *                      monotonicity, bounds), including degenerate input.
 *   3. Calibration  -- Monte Carlo checks that the false-positive rate under a
 *                      true null is what we claim, and that BH controls FDR.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  Z_95,
  benjaminiHochberg,
  binomialTailP,
  cliffsDelta,
  cohensD,
  erf,
  erfc,
  gaussian,
  incompleteBeta,
  ksTest,
  leveneTest,
  logGamma,
  mannWhitneyU,
  mean,
  median,
  normalCdf,
  quantile,
  seededRandom,
  stdev,
  tDistTwoSided,
  variance,
  welchTTest,
  wilsonInterval,
} from '../src/stats.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const REF = JSON.parse(
  readFileSync(join(HERE, 'fixtures', 'scipy-reference.json'), 'utf8'),
);

/** Assert `actual` is within `tol` of `expected`, reporting the shortfall. */
function near(actual, expected, tol, label) {
  const diff = Math.abs(actual - expected);
  assert.ok(
    Number.isFinite(actual) && diff <= tol,
    `${label}: got ${actual}, expected ${expected} (|diff| ${diff.toExponential(3)} > ${tol.toExponential(3)})`,
  );
}

/** Assert `actual` is within a RELATIVE tolerance of `expected`. */
function nearRel(actual, expected, tol, label) {
  const diff = expected === 0
    ? Math.abs(actual)
    : Math.abs(actual - expected) / Math.abs(expected);
  assert.ok(
    Number.isFinite(actual) && diff <= tol,
    `${label}: got ${actual}, expected ${expected} (rel ${diff.toExponential(3)} > ${tol.toExponential(3)})`,
  );
}

/* ------------------------------------------------------------------ *
 * 1. Conformance with SciPy
 * ------------------------------------------------------------------ */

test('special functions match SciPy', async (t) => {
  await t.test('logGamma matches scipy.special.gammaln, both branches', () => {
    // x < 0.5 takes the reflection formula; x >= 0.5 takes Lanczos directly.
    // The fixture straddles the boundary deliberately.
    REF.logGamma.x.forEach((x, i) => {
      nearRel(logGamma(x), REF.logGamma.v[i], 1e-13, `logGamma(${x})`);
    });
    // Γ(n) = (n-1)! gives an independent check with no reference data.
    near(Math.exp(logGamma(5)), 24, 1e-9, 'logGamma(5) => 4!');
    near(Math.exp(logGamma(0.5)), Math.sqrt(Math.PI), 1e-12, 'logGamma(1/2) => sqrt(pi)');
  });

  await t.test('erf matches scipy.special.erf to machine precision', () => {
    REF.erf.x.forEach((x, i) => {
      nearRel(erf(x), REF.erf.v[i], 1e-13, `erf(${x})`);
    });
  });

  await t.test('erfc keeps precision in the tail where 1-erf(x) cannot', () => {
    // erfc(20) is ~5.4e-176. Computing it as 1 - erf(20) yields exactly 0 and
    // silently destroys any deep-tail p-value built on top of it.
    REF.erfc.x.forEach((x, i) => {
      nearRel(erfc(x), REF.erfc.v[i], 1e-12, `erfc(${x})`);
    });
    assert.ok(erfc(20) > 0, 'erfc must not underflow to zero at x=20');
  });

  await t.test('normalCdf matches scipy.stats.norm.cdf, including the deep tail', () => {
    // Relative tolerance, not absolute: norm.cdf(-40) is ~7e-350, and an
    // absolute check would pass trivially while the value was garbage.
    REF.normalCdf.z.forEach((z, i) => {
      nearRel(normalCdf(z), REF.normalCdf.v[i], 1e-12, `normalCdf(${z})`);
    });
  });

  await t.test('erf and normalCdf are exact at their symmetry points', () => {
    // An approximation that returns 1e-9 here is a red flag: it means the
    // whole function is only good to ~1e-7, which is not enough for the
    // Mann-Whitney and KS p-values layered on top of it.
    assert.equal(erf(0), 0, 'erf(0) must be exactly 0');
    assert.equal(normalCdf(0), 0.5, 'normalCdf(0) must be exactly 0.5');
    for (const x of [0.1, 0.5, 1, 2, 3.5]) {
      near(erf(-x), -erf(x), 1e-15, `erf odd symmetry at ${x}`);
      assert.ok(erf(x) > 0 && erf(x) < 1, `erf(${x}) in (0,1)`);
    }
    for (const z of [0.3, 1, 2.5, 5]) {
      near(normalCdf(z) + normalCdf(-z), 1, 1e-15, `normalCdf symmetry at ${z}`);
    }
    near(erf(10), 1, 1e-15, 'erf saturates to 1');
  });

  await t.test('tDistTwoSided matches 2*scipy.stats.t.sf', () => {
    for (const [tStat, df, expected] of REF.tdist.cases) {
      near(tDistTwoSided(tStat, df), expected, 1e-10, `t(${tStat}, df=${df})`);
    }
  });

  await t.test('Z_95 is the true 97.5th normal percentile', () => {
    // A rounded 1.96 shifts interval endpoints in the 6th decimal, which is
    // enough to disagree with statsmodels. Confirm we kept full precision.
    near(normalCdf(Z_95), 0.975, 1e-7, 'normalCdf(Z_95)');
  });
});

test('descriptive statistics match NumPy', async (t) => {
  await t.test('quantile matches numpy method="linear"', () => {
    const { data, qs, vals } = REF.quantile;
    qs.forEach((q, i) => {
      near(quantile(data, q), vals[i], 1e-12, `quantile(${q})`);
    });
  });

  await t.test('mean, variance and stdev are the n-1 estimators', () => {
    const xs = [2, 4, 4, 4, 5, 5, 7, 9];
    near(mean(xs), 5, 1e-12, 'mean');
    // Population variance is 4; the sample (n-1) estimator is 32/7.
    near(variance(xs), 32 / 7, 1e-12, 'variance is unbiased (n-1)');
    near(stdev(xs), Math.sqrt(32 / 7), 1e-12, 'stdev');
  });

  await t.test('median handles odd and even lengths without mutating input', () => {
    const xs = [3, 1, 2];
    near(median(xs), 2, 0, 'odd-length median');
    assert.deepEqual(xs, [3, 1, 2], 'median must not sort the caller array');
    near(median([4, 1, 3, 2]), 2.5, 0, 'even-length median averages the middle pair');
  });
});

test('two-sample tests match SciPy across realistic probe scenarios', async (t) => {
  for (const c of REF.twoSample) {
    await t.test(c.name, () => {
      const w = welchTTest(c.a, c.b);
      near(w.t, c.welch_t, 1e-9, 'Welch t');
      near(w.df, c.welch_df, 1e-7, 'Welch-Satterthwaite df');
      near(w.p, c.welch_p, 1e-9, 'Welch p');

      // Mann-Whitney: normal approximation with tie correction and continuity
      // correction. SciPy's asymptotic method does the same, so agreement
      // should be tight even in the heavily-tied binary case.
      const m = mannWhitneyU(c.a, c.b);
      near(m.p, c.mw_p, 1e-6, 'Mann-Whitney p');

      const k = ksTest(c.a, c.b);
      near(k.d, c.ks_d, 1e-12, 'KS D');
      // We use the exact kstwo distribution in the decision-relevant range and
      // fall back to the asymptotic limit only once p is already < 1e-4, where
      // the two differ by far less than any threshold cares about.
      const ksTol = c.ks_p < 1e-4 ? 1e-3 : 1e-6;
      near(k.p, c.ks_p, ksTol, 'KS p');

      const l = leveneTest(c.a, c.b);
      near(l.w, c.lev_w, 1e-7, 'Levene W (Brown-Forsythe)');
      near(l.p, c.lev_p, 1e-7, 'Levene p');
    });
  }
});

test('KS stays numerically stable when the exact matrix power gets large', () => {
  // The exact method raises a (2k-1)^2 matrix to the n-th power; without
  // periodic rescaling the entries overflow to Infinity and the p-value
  // becomes NaN. Drive n and D high enough to exercise that rescaling.
  // Large n with a SMALL D is the demanding case: the matrix stays inside the
  // exact-method window and gets raised to a high power, so intermediate
  // entries reach ~1e258 against a 1.8e308 ceiling. Without the rescaling step
  // these overflow to Infinity and every p-value comes back NaN.
  const rnd = seededRandom(90210);
  for (const n of [700, 1000, 1500]) {
    for (const shift of [0.02, 0.08, 0.15]) {
      const a = Array.from({ length: n }, () => gaussian(rnd, 0, 1));
      const b = Array.from({ length: n }, () => gaussian(rnd, shift, 1));
      const { d, p } = ksTest(a, b);
      const at = `n=${n}, shift=${shift}`;
      assert.ok(Number.isFinite(p) && p >= 0 && p <= 1, `${at}: p=${p} is not a probability`);
      assert.ok(Number.isFinite(d) && d >= 0 && d <= 1, `${at}: D=${d} is not a distance`);
    }
  }

  // And it must still be numerically correct there, not merely finite.
  const big = REF.twoSample.find((x) => x.name === 'tiny_effect_bign');
  near(ksTest(big.a, big.b).p, big.ks_p, 1e-5, 'large-sample KS p stays accurate');
});

test('KS uses the exact distribution where it changes decisions', () => {
  // n=8 vs n=9. Asymptotic Kolmogorov gives p=0.0171; the exact kstwo
  // distribution gives p=0.0078. Both are "significant" at 0.05, but the
  // asymptotic value is more than twice as large, and at a stricter threshold
  // or after BH adjustment that gap decides whether we alert.
  const c = REF.twoSample.find((x) => x.name === 'small_n');
  const { p } = ksTest(c.a, c.b);
  near(p, c.ks_p, 1e-9, 'small-sample KS p is exact');
  assert.ok(p < 0.01, 'exact small-sample p should not be inflated toward 0.017');
});

test('effect sizes match brute-force and SciPy definitions', async (t) => {
  await t.test("Cliff's delta matches the O(n*m) definition", () => {
    // stats.js computes this in O(n log n) via binary search; the fixture is
    // the literal pairwise-dominance count. They must agree exactly.
    for (const { name, delta } of REF.cliffs) {
      const c = REF.twoSample.find((x) => x.name === name);
      near(cliffsDelta(c.a, c.b), delta, 1e-12, `cliffsDelta(${name})`);
    }
  });

  await t.test("Cliff's delta is bounded, antisymmetric and correctly signed", () => {
    assert.equal(cliffsDelta([1, 2, 3], [10, 20, 30]), -1, 'fully dominated = -1');
    assert.equal(cliffsDelta([10, 20, 30], [1, 2, 3]), 1, 'fully dominating = +1');
    assert.equal(cliffsDelta([1, 2, 3], [1, 2, 3]), 0, 'identical samples = 0');
    for (const { name } of REF.cliffs) {
      const c = REF.twoSample.find((x) => x.name === name);
      const d = cliffsDelta(c.a, c.b);
      assert.ok(d >= -1 && d <= 1, `${name}: delta within [-1, 1]`);
      near(cliffsDelta(c.b, c.a), -d, 1e-12, `${name}: antisymmetry`);
    }
  });

  await t.test("Cohen's d matches the pooled-SD definition", () => {
    near(cohensD(REF.cohensD.a, REF.cohensD.b), REF.cohensD.d, 1e-12, "Cohen's d");
  });
});

/* ------------------------------------------------------------------ *
 * 2. Multiplicity control and interval estimation
 * ------------------------------------------------------------------ */

test('Benjamini-Hochberg matches statsmodels fdr_bh', async (t) => {
  await t.test('adjusted p-values agree on every fixture set', () => {
    for (const { p, adj } of REF.benjaminiHochberg) {
      const got = benjaminiHochberg(p);
      assert.equal(got.length, p.length, 'one adjusted value per input');
      adj.forEach((expected, i) => {
        near(got[i], expected, 1e-12, `BH[n=${p.length}][${i}]`);
      });
    }
  });

  await t.test('adjusted values are returned in caller order, not sorted order', () => {
    // This is the single easiest BH bug to ship: sorting internally and
    // forgetting to invert the permutation silently reassigns each p-value to
    // the wrong probe, so we would name the wrong metric as the drift signal.
    const p = [0.9, 0.001, 0.5];
    const adj = benjaminiHochberg(p);
    assert.ok(adj[1] < adj[0] && adj[1] < adj[2], 'smallest input keeps smallest adjusted value');
    near(adj[1], 0.003, 1e-12, 'BH: 0.001 * 3/1');
  });

  await t.test('adjusted p-values are monotone in the sorted p-values', () => {
    const rnd = seededRandom(99);
    const p = Array.from({ length: 200 }, () => rnd());
    const idx = p.map((_, i) => i).sort((x, y) => p[x] - p[y]);
    const adj = benjaminiHochberg(p);
    for (let i = 1; i < idx.length; i++) {
      assert.ok(
        adj[idx[i]] >= adj[idx[i - 1]] - 1e-12,
        `step-up monotonicity violated at rank ${i}`,
      );
    }
  });

  await t.test('adjusted p-values never shrink and never exceed 1', () => {
    const rnd = seededRandom(7);
    const p = Array.from({ length: 500 }, () => rnd());
    benjaminiHochberg(p).forEach((a, i) => {
      assert.ok(a >= p[i] - 1e-12, `BH must not decrease p[${i}]`);
      assert.ok(a <= 1, `BH must stay <= 1 at ${i}`);
    });
  });

  await t.test('empty input yields empty output', () => {
    assert.deepEqual(benjaminiHochberg([]), []);
  });
});

test('Wilson intervals match statsmodels', async (t) => {
  await t.test('endpoints agree on the fixture cases', () => {
    for (const { s, n, lower, upper } of REF.wilson) {
      const r = wilsonInterval(s, n);
      near(r.lower, lower, 1e-9, `wilson(${s}/${n}).lower`);
      near(r.upper, upper, 1e-9, `wilson(${s}/${n}).upper`);
    }
  });

  await t.test('zero observed events still yields an honest upper bound', () => {
    // This is how we report a null alert rate. "0 false alarms in 500 cycles"
    // is not evidence of a 0% rate, and a Wald interval would claim [0, 0].
    const r = wilsonInterval(0, 500);
    near(r.lower, 0, 1e-12, 'lower bound is 0');
    assert.ok(r.upper > 0.005 && r.upper < 0.01, `upper bound ~0.76%, got ${r.upper}`);
  });

  await t.test('intervals are ordered, bounded and contain the point estimate', () => {
    for (const n of [1, 5, 20, 100, 1000]) {
      for (let s = 0; s <= n; s += Math.max(1, Math.floor(n / 7))) {
        const { lower, upper } = wilsonInterval(s, n);
        assert.ok(lower >= 0 && upper <= 1, `wilson(${s}/${n}) within [0,1]`);
        assert.ok(lower <= upper, `wilson(${s}/${n}) ordered`);
        assert.ok(
          lower <= s / n + 1e-12 && upper >= s / n - 1e-12,
          `wilson(${s}/${n}) contains p-hat`,
        );
      }
    }
  });

  await t.test('a zero-trial denominator does not produce NaN', () => {
    const r = wilsonInterval(0, 0);
    assert.ok(Number.isFinite(r.lower) && Number.isFinite(r.upper), 'no NaN on n=0');
  });
});

test('exact binomial tail matches scipy', async (t) => {
  await t.test('fixture cases agree to near machine precision', () => {
    for (const [k, n, p0, expected] of REF.binomialTail.cases) {
      nearRel(binomialTailP(k, n, p0), expected, 1e-11, `binomTail(${k},${n},${p0})`);
    }
  });

  await t.test('stays exact deep in the tail where naive summation underflows', () => {
    // 25 of 50 tenants agreeing at a 9% chance rate is a ~1e-13 event. This is
    // the regime every published change event lives in, so the estimator has
    // to be accurate there rather than merely returning zero.
    const truth = REF.binomialTail.cases.find(([k, n, p0]) => k === 25 && n === 50 && p0 === 0.09);
    assert.ok(truth, 'fixture must carry the deep-tail case');
    const p = binomialTailP(25, 50, 0.09);
    assert.ok(p > 0, 'must not underflow to zero');
    assert.ok(p < 1e-12, 'and must actually be in the deep tail');
    nearRel(p, truth[3], 1e-11, 'deep tail');
  });

  await t.test('is monotone in k, n and p0', () => {
    for (let k = 1; k < 20; k++) {
      assert.ok(
        binomialTailP(k + 1, 40, 0.1) <= binomialTailP(k, 40, 0.1),
        'requiring more agreement cannot become more likely',
      );
    }
    for (const p0 of [0.01, 0.05, 0.1, 0.3]) {
      assert.ok(binomialTailP(5, 50, p0) <= binomialTailP(5, 50, p0 + 0.05));
    }
    // More tenants makes any fixed count easier to reach by chance -- the
    // exact effect that breaks fixed-threshold corroboration rules.
    for (const n of [10, 20, 50, 100, 300]) {
      assert.ok(binomialTailP(5, n, 0.1) <= binomialTailP(5, n * 2, 0.1));
    }
  });

  await t.test('degenerate inputs are safe', () => {
    assert.equal(binomialTailP(0, 10, 0.1), 1, 'P(X >= 0) is certain');
    assert.equal(binomialTailP(11, 10, 0.1), 0, 'cannot exceed the trial count');
    assert.equal(binomialTailP(1, 0, 0.1), 1);
    assert.equal(binomialTailP(1, 10, 0), 0);
    assert.equal(binomialTailP(1, 10, 1), 1);
    nearRel(binomialTailP(50, 50, 0.5), Math.pow(0.5, 50), 1e-11, 'unanimity');
  });

  await t.test('I_x(a,b) does not hang on the symmetry boundary', () => {
    // Regression guard. The continued fraction swaps to I_{1-x}(b,a) above a
    // threshold; when x sits exactly on it, a non-strict comparison recurses
    // until the stack dies. I_0.5(1,1) is the smallest case that lands there.
    nearRel(incompleteBeta(0.5, 1, 1), 0.5, 1e-12, 'I_0.5(1,1)');
    nearRel(binomialTailP(1, 1, 0.5), 0.5, 1e-12, 'the boundary case');
  });
});

/* ------------------------------------------------------------------ *
 * 3. Universal properties and degenerate input
 * ------------------------------------------------------------------ */

test('every test returns a valid p-value on degenerate input', () => {
  // Probe batteries produce these constantly: a metric that never varies
  // (JSON validity 100% on both sides), a single retained sample, an empty
  // window after filtering. None may yield NaN, throw, or alert.
  const cases = [
    ['identical', [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]],
    ['both constant, equal', [5, 5, 5, 5], [5, 5, 5, 5]],
    ['both constant, different', [5, 5, 5, 5], [9, 9, 9, 9]],
    ['one constant', [5, 5, 5, 5], [1, 5, 9, 3]],
    ['singleton vs singleton', [1], [2]],
    ['singleton vs many', [3], [1, 2, 3, 4, 5, 6, 7, 8]],
    ['empty vs populated', [], [1, 2, 3]],
    ['both empty', [], []],
    ['disjoint ranges', [1, 2, 3], [100, 200, 300]],
    ['negative values', [-5, -3, -1], [-4, -2, 0]],
    ['huge magnitudes', [1e12, 2e12, 3e12], [1e12, 2e12, 3.1e12]],
    ['tiny magnitudes', [1e-12, 2e-12, 3e-12], [1.1e-12, 2e-12, 3e-12]],
  ];

  for (const [name, a, b] of cases) {
    for (const [fn, label] of [
      [welchTTest, 'welchTTest'],
      [mannWhitneyU, 'mannWhitneyU'],
      [ksTest, 'ksTest'],
      [leveneTest, 'leveneTest'],
    ]) {
      const { p } = fn(a, b);
      assert.ok(
        Number.isFinite(p) && p >= 0 && p <= 1,
        `${label} on "${name}" returned invalid p=${p}`,
      );
    }
    const d = cliffsDelta(a, b);
    assert.ok(Number.isFinite(d) && d >= -1 && d <= 1, `cliffsDelta on "${name}" = ${d}`);
  }
});

test('identical samples are never flagged as different', () => {
  const rnd = seededRandom(1234);
  const xs = Array.from({ length: 60 }, () => gaussian(rnd, 10, 2));
  assert.equal(welchTTest(xs, xs).p, 1, 'Welch p = 1 on identical input');
  assert.equal(ksTest(xs, xs).d, 0, 'KS D = 0 on identical input');
  assert.equal(cliffsDelta(xs, xs), 0, 'delta = 0 on identical input');
  assert.ok(mannWhitneyU(xs, xs).p > 0.99, 'Mann-Whitney p ~ 1 on identical input');
  assert.ok(leveneTest(xs, xs).p > 0.99, 'Levene p ~ 1 on identical input');
});

test('tests are symmetric in their arguments', () => {
  const rnd = seededRandom(555);
  const a = Array.from({ length: 45 }, () => gaussian(rnd, 0, 1));
  const b = Array.from({ length: 52 }, () => gaussian(rnd, 0.4, 1.3));
  near(welchTTest(a, b).p, welchTTest(b, a).p, 1e-12, 'Welch p symmetric');
  near(mannWhitneyU(a, b).p, mannWhitneyU(b, a).p, 1e-12, 'Mann-Whitney p symmetric');
  near(ksTest(a, b).p, ksTest(b, a).p, 1e-12, 'KS p symmetric');
  near(leveneTest(a, b).p, leveneTest(b, a).p, 1e-12, 'Levene p symmetric');
});

test('p-values decrease monotonically as a real shift grows', () => {
  // Sanity on the direction of the machinery: a bigger change must not look
  // less significant.
  const rnd = seededRandom(31337);
  const base = Array.from({ length: 80 }, () => gaussian(rnd, 0, 1));
  let previous = 1;
  for (const shift of [0, 0.25, 0.5, 1, 2, 4]) {
    const shifted = base.map((x) => x + shift);
    const p = welchTTest(base, shifted).p;
    assert.ok(p <= previous + 1e-12, `p rose when shift grew to ${shift}`);
    previous = p;
  }
  assert.ok(previous < 1e-20, 'a 4-sigma shift must be overwhelmingly significant');
});

test('each test detects the alternative it exists to catch', async (t) => {
  const rnd = seededRandom(2718);
  const sample = (n, m, s) => Array.from({ length: n }, () => gaussian(rnd, m, s));

  await t.test('Welch catches a mean shift', () => {
    assert.ok(welchTTest(sample(120, 0, 1), sample(120, 0.6, 1)).p < 1e-4);
  });

  await t.test('Levene catches a variance change at constant mean', () => {
    // Mean is unchanged, so Welch should be unconvinced while Levene fires.
    const a = sample(150, 0, 1);
    const b = sample(150, 0, 3);
    assert.ok(leveneTest(a, b).p < 1e-6, 'Levene detects the scale change');
    assert.ok(welchTTest(a, b).p > 0.01, 'Welch is not fooled into a mean claim');
  });

  await t.test('KS catches a shape change at constant mean and variance', () => {
    // Bimodal versus unimodal with matched moments: only a distributional
    // test can see this. It is the "same average verbosity, different
    // behaviour" case that motivates having KS at all.
    const uni = sample(200, 0, 1);
    const bi = Array.from({ length: 200 }, (_, i) =>
      i % 2 === 0 ? gaussian(rnd, -1, 0.15) : gaussian(rnd, 1, 0.15));
    const shape = ksTest(uni, bi);
    assert.ok(shape.p < 1e-4, `KS detects the shape change (p=${shape.p})`);
    assert.ok(shape.d > 0.2, `KS D reflects the separation (D=${shape.d})`);
  });

  await t.test('Mann-Whitney survives heavy ties', () => {
    // Binary probe outcomes (valid JSON or not) are almost all ties, which is
    // exactly where an uncorrected variance term breaks down.
    const a = Array.from({ length: 200 }, () => (rnd() < 0.95 ? 1 : 0));
    const b = Array.from({ length: 200 }, () => (rnd() < 0.70 ? 1 : 0));
    assert.ok(mannWhitneyU(a, b).p < 1e-6, 'tie-corrected variance still detects');
  });
});

/* ------------------------------------------------------------------ *
 * 4. Calibration under the null -- the false-alarm budget
 * ------------------------------------------------------------------ */

test('seeded PRNG is deterministic and well-behaved', async (t) => {
  await t.test('same seed reproduces the same stream', () => {
    const a = Array.from({ length: 50 }, seededRandom(42));
    const b = Array.from({ length: 50 }, seededRandom(42));
    assert.deepEqual(a, b, 'seeded streams must be reproducible');
    assert.notDeepEqual(a, Array.from({ length: 50 }, seededRandom(43)));
  });

  await t.test('output stays in [0,1) with a plausible mean', () => {
    const rnd = seededRandom(8);
    let sum = 0;
    for (let i = 0; i < 100000; i++) {
      const x = rnd();
      assert.ok(x >= 0 && x < 1, `PRNG escaped [0,1): ${x}`);
      sum += x;
    }
    near(sum / 100000, 0.5, 0.01, 'PRNG mean');
  });

  await t.test('gaussian produces the requested moments', () => {
    const rnd = seededRandom(11);
    const xs = Array.from({ length: 200000 }, () => gaussian(rnd, 5, 2));
    near(mean(xs), 5, 0.02, 'gaussian mean');
    near(stdev(xs), 2, 0.02, 'gaussian sd');
  });
});

test('false-positive rate under a true null matches the nominal alpha', () => {
  // The product promise is a low false-alarm rate. If these tests were
  // miscalibrated, Sentinel would invent drift events out of pure noise.
  // Draw both samples from the SAME distribution and count rejections.
  const rnd = seededRandom(20260819);
  const TRIALS = 2000;
  const ALPHA = 0.05;
  const counts = { welch: 0, mw: 0, ks: 0, levene: 0 };

  for (let i = 0; i < TRIALS; i++) {
    const a = Array.from({ length: 40 }, () => gaussian(rnd, 100, 12));
    const b = Array.from({ length: 40 }, () => gaussian(rnd, 100, 12));
    if (welchTTest(a, b).p < ALPHA) counts.welch++;
    if (mannWhitneyU(a, b).p < ALPHA) counts.mw++;
    if (ksTest(a, b).p < ALPHA) counts.ks++;
    if (leveneTest(a, b).p < ALPHA) counts.levene++;
  }

  for (const [name, hits] of Object.entries(counts)) {
    const { lower, upper } = wilsonInterval(hits, TRIALS);
    // Nominal 5%. KS on continuous data is known to be conservative, so we
    // require the interval to sit at or below alpha rather than straddle it.
    assert.ok(
      lower <= ALPHA + 0.005 && upper >= 0.01,
      `${name}: empirical FPR ${(hits / TRIALS).toFixed(4)} `
        + `[${lower.toFixed(4)}, ${upper.toFixed(4)}] is not consistent with alpha=${ALPHA}`,
    );
    assert.ok(
      hits / TRIALS < 0.09,
      `${name}: FPR ${(hits / TRIALS).toFixed(4)} is unacceptably above alpha=${ALPHA}`,
    );
  }
});

test('p-values are uniform under the null', () => {
  // A correct continuous test yields p ~ Uniform(0,1) when nothing changed.
  // Checking the whole distribution, not just the 5% tail, catches systematic
  // mis-scaling that a single-threshold check would miss.
  const rnd = seededRandom(4711);
  const TRIALS = 3000;
  const ps = [];
  for (let i = 0; i < TRIALS; i++) {
    const a = Array.from({ length: 35 }, () => gaussian(rnd, 0, 1));
    const b = Array.from({ length: 35 }, () => gaussian(rnd, 0, 1));
    ps.push(welchTTest(a, b).p);
  }
  ps.sort((x, y) => x - y);

  // Kolmogorov-Smirnov one-sample check against Uniform(0,1).
  let dMax = 0;
  ps.forEach((p, i) => {
    dMax = Math.max(dMax, Math.abs((i + 1) / TRIALS - p), Math.abs(p - i / TRIALS));
  });
  const critical = 1.63 / Math.sqrt(TRIALS); // ~99% critical value
  assert.ok(
    dMax < critical,
    `Welch p-values deviate from Uniform(0,1): D=${dMax.toFixed(4)} >= ${critical.toFixed(4)}`,
  );

  for (const q of [0.1, 0.25, 0.5, 0.75, 0.9]) {
    near(quantile(ps, q), q, 0.04, `null p-value ${q} quantile`);
  }
});

test('Benjamini-Hochberg controls FDR across a realistic probe battery', () => {
  // A single cycle runs dozens of probe x metric comparisons. At alpha=0.05
  // and 40 null comparisons, uncorrected testing manufactures a false "drift
  // event" in most cycles. This is the whole reason BH is in the pipeline.
  const rnd = seededRandom(31415);
  const CYCLES = 400;
  const NULL_PROBES = 40;

  let cyclesWithUncorrectedHit = 0;
  let cyclesWithCorrectedHit = 0;

  for (let c = 0; c < CYCLES; c++) {
    const ps = [];
    for (let i = 0; i < NULL_PROBES; i++) {
      const a = Array.from({ length: 30 }, () => gaussian(rnd, 1, 0.2));
      const b = Array.from({ length: 30 }, () => gaussian(rnd, 1, 0.2));
      ps.push(welchTTest(a, b).p);
    }
    if (ps.some((p) => p < 0.05)) cyclesWithUncorrectedHit++;
    if (benjaminiHochberg(ps).some((p) => p < 0.05)) cyclesWithCorrectedHit++;
  }

  const rawRate = cyclesWithUncorrectedHit / CYCLES;
  const bhRate = cyclesWithCorrectedHit / CYCLES;

  assert.ok(
    rawRate > 0.5,
    `expected uncorrected testing to be badly inflated, got ${rawRate.toFixed(3)}`,
  );
  assert.ok(
    bhRate <= 0.08,
    `BH failed to control the per-cycle false-discovery rate: ${bhRate.toFixed(3)}`,
  );
});

test('BH still recovers true effects when they are present', () => {
  // Controlling false alarms is worthless if it also suppresses real drift.
  // 40 comparisons, 8 of which carry a genuine shift.
  const rnd = seededRandom(2024);
  const ps = [];
  for (let i = 0; i < 40; i++) {
    const shifted = i < 8;
    const a = Array.from({ length: 60 }, () => gaussian(rnd, 1, 0.2));
    const b = Array.from({ length: 60 }, () => gaussian(rnd, shifted ? 1.2 : 1, 0.2));
    ps.push(welchTTest(a, b).p);
  }
  const adj = benjaminiHochberg(ps);
  const detected = adj.slice(0, 8).filter((p) => p < 0.05).length;
  const falsePositives = adj.slice(8).filter((p) => p < 0.05).length;

  assert.ok(detected >= 7, `BH recovered only ${detected}/8 true effects`);
  assert.ok(falsePositives <= 2, `BH admitted ${falsePositives} false discoveries`);
});

test('effect size and significance disagree on large samples', () => {
  // The reason stats.js pairs every test with an effect size: at n=5000 a
  // negligible 0.02-sigma difference is "highly significant". Alerting on the
  // p-value alone would page a customer over nothing.
  const rnd = seededRandom(6060);
  const a = Array.from({ length: 5000 }, () => gaussian(rnd, 1, 0.2));
  const b = Array.from({ length: 5000 }, () => gaussian(rnd, 1.008, 0.2));

  const { p } = welchTTest(a, b);
  const delta = Math.abs(cliffsDelta(a, b));

  assert.ok(p < 0.05, 'the shift is statistically detectable at this sample size');
  assert.ok(
    delta < 0.147,
    `Cliff's delta ${delta.toFixed(4)} should be below the 0.147 "negligible" threshold`,
  );
});
